services:
  service_8000:
    build: ./microservices
    container_name: service_8000
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - backbone

  service_8001:
    build: ./microservices
    container_name: service_8001
    ports:
      - "8001:8000"
    environment:
      - PORT=8001
    networks:
      - backbone

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=admin
    command: redis-server --requirepass $${REDIS_PASSWORD}
    networks:
      - backbone

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: dbname
    networks:
      - backbone

volumes:
  redis_data:
  mongodb_data:

networks:
  backbone:
    driver: bridge